### ISSUE TITLE
训练效率的疑问？

### ISSUE THREAD

**Issue by IDayday** [lzzmm/breakout#1]
您好，看了您在B站上的演示视频，我对您的训练过程非常感兴趣。我目前实现了一版近似DQN的算法，网络结构仅仅是小幅改动。但我的训练效率异常低下。特别的，breakout环境交互过程中，steps数累加得非常慢，进而导致update缓慢。具体log如下：

>09:28:30 AM > ep 12889 done. total_steps=712610 | reward=2.0 | episode_steps=127 | hours=7.224 | epsilon=0.520
09:28:34 AM > ep 12890 done. total_steps=712706 | reward=1.0 | episode_steps=96 | hours=7.225 | epsilon=0.520
09:28:36 AM > ep 12891 done. total_steps=712737 | reward=0.0 | episode_steps=31 | hours=7.225 | epsilon=0.520
09:28:36 AM > ep 12892 done. total_steps=712767 | reward=0.0 | episode_steps=30 | hours=7.225 | epsilon=0.520
09:28:39 AM > ep 12893 done. total_steps=712863 | reward=1.0 | episode_steps=96 | hours=7.226 | epsilon=0.520
09:28:44 AM > ep 12894 done. total_steps=712992 | reward=2.0 | episode_steps=129 | hours=7.227 | epsilon=0.520
09:28:45 AM > ep 12895 done. total_steps=713023 | reward=0.0 | episode_steps=31 | hours=7.228 | epsilon=0.520
09:28:46 AM > ep 12896 done. total_steps=713052 | reward=0.0 | episode_steps=29 | hours=7.228 | epsilon=0.520
9:28:48 AM > ep 12897 done. total_steps=713083 | reward=0.0 | episode_steps=31 | hours=7.228 | epsilon=0.520
09:28:49 AM > ep 12898 done. total_steps=713119 | reward=0.0 | episode_steps=36 | hours=7.229 | epsilon=0.520

**20s仅仅生成539steps，7个多小时的训练总步数仅有0.7M**

* 我使用的硬件是
* 英特尔至强铂金CPU-20核40线程
* A100GPU

我观察到您的源码也未使用多线程加速采样，所以我想问问您对这个现象的看法
期待您的回复

**Comment by lzzmm** [comment]
您好。
就您提供的信息我也看不太出具体的问题，这个项目本质上只是上学期的强化学习课程期中作业，完成度不高，只是老师要求公开🤣
我可以提供如下猜测：
1. 在训练中我们发现 CPU 好像确实是训练速度的瓶颈，我们使用 V100 GPU， 显存占用和计算核心负载都很低；
2. 您的 epsilon 似乎很大，这可能导致需要更加频繁地计算随机方向；
3. 您可以观察一下训练时 CPU 的负载，不排除可能程序中有错误，就我们的经验来讲每秒至少可以运算数百次游戏；
  ![image](https://user-images.githubusercontent.com/25279349/163672285-ee751f46-b9d9-4566-90d4-003539cb82ad.png)
4. 您可以尝试使用多线程来加速训练，因为我们的作业时间比较紧急，所以代码写的并不细致。
欢迎更进一步的讨论，也期待您的好消息。
顺颂春祺。

**Comment by IDayday** [comment]
> 您好。 就您提供的信息我也看不太出具体的问题，这个项目本质上只是上学期的强化学习课程期中作业，完成度不高，只是老师要求公开🤣 我可以提供如下猜测：
> 
> 1. 在训练中我们发现 CPU 好像确实是训练速度的瓶颈，我们使用 V100 GPU， 显存占用和计算核心负载都很低；
> 2. 您的 epsilon 似乎很大，这可能导致需要更加频繁地计算随机方向；
> 3. 您可以观察一下训练时 CPU 的负载，不排除可能程序中有错误，就我们的经验来讲每秒至少可以运算数百次游戏；
>    ![image](https://user-images.githubusercontent.com/25279349/163672285-ee751f46-b9d9-4566-90d4-003539cb82ad.png)
> 4. 您可以尝试使用多线程来加速训练，因为我们的作业时间比较紧急，所以代码写的并不细致。
>    欢迎更进一步的讨论，也期待您的好消息。
>    顺颂春祺。

谢谢您的回复，我已尽可能优化迭代速度，不过还是比DQN慢一点。
